### ISSUE TITLE
Support for multiple Terraform modules.

### ISSUE THREAD

**Issue by MrJoy** [infracost/infracost-gh-action#16]
Because of its performance characteristics, a best-practice at every org I've been involved in is to have multiple separate Terraform modules.  That could be per-environment, or per-environment-per-system.  In my case, I have 3 modules for AWS (one per env), 3 for GCP (one per env; soon to be 4), and so on (we also use the DataDog, and Github providers with plans to add a couple more).  Looking at the source to this action, I don't see a means to handle this.

If such a mechanism exists, can you point me at relevant documentation?  If such a mechanism does not exist, I'd love to see it added.

**Comment by aliscott** [comment]
@MrJoy thanks! I added this doc to explain what happens just now (https://www.infracost.io/docs/terraform_modules)

Are you wanting to see a cost difference for a specific module or are you wanting to see how the change affects each different module, i.e. "This change will increase the monthly cost on prod by X%" and "This change will increase the monthly cost on dev by X%".? To show a diff for each module individually one workaround at the moment could be to run the action twice with different inputs.

**Comment by MrJoy** [comment]
Showing change per-module (on modules whose source or dependencies have changed) seems a reasonable option.  Can the same action be added multiple times with different inputs?  I'll see about giving that a shot once I have time to circle back around to CI/CD stuff.

**Comment by MrJoy** [comment]
Ah, sorry.  I think I've confused the issue by abusing terminology.

When I said "module", I misspoke.  I mean separate Terraform _projects_ -- I.E. things with separate state files.  There are modules shared between them, and I don't especially care about the modules individually.  I only care about seeing changes as they pertain to the array of separate Terraform states that I have.

**Comment by MrJoy** [comment]
To be a bit more explicit, this is a subset of what our infra repo's layout looks like (the `.terraform` directories are not versioned, they're included for illustrative purposes):

```bash
...
./gcp
./gcp/environments
./gcp/environments/development
./gcp/environments/development/.terraform # Has its own state on GCP.
./gcp/environments/meta
./gcp/environments/meta/.terraform # Has its own state on GCP.
./gcp/environments/stage
./gcp/environments/stage/.terraform # Has its own state on GCP.
./gcp/modules # Shared modules used by multiple environments...
...
./aws
./aws/environments
./aws/environments/prod
./aws/environments/prod/.terraform # Has its own state on AWS.
./aws/environments/meta
./aws/environments/meta/.terraform # Has its own state on AWS.
./aws/environments/stage
./aws/environments/stage/.terraform # Has its own state on AWS.
./aws/modules # Shared modules used by multiple environments...
...
```

**Comment by MrJoy** [comment]
So I would ideally see, like you said, GCP Development changed by X% if I change source files in `gcp/environments/development`, or anything in `gcp/modules` that's used from `gcp/environments/development`.

**Comment by alikhajeh1** [comment]
hmm this smells like https://github.com/infracost/infracost/issues/188, so **if** [report_all.sh](https://www.infracost.io/docs/report#bulk-run) could be run in CI with `table` output, then we could do the `git diff` on that combined report, and show the "changed by X%". @MrJoy am I right or am I right? (lol, I'm probably missing something)

**Comment by MrJoy** [comment]
Mostly.  In our case, we're using Terraform providers other than just GCP and AWS (Github, Datadog), so including all directories not named `modules` containing `.tf` files is going to lead to a lot of needless CPU-tim and complexity around secrets management / errors, etc.

**Comment by aliscott** [comment]
@MrJoy we're looking at adding a config file you can pass to Infracost where you can specify multiple projects and combine them into one report/PR comment with any changes grouped by the project. Would something like this help your use case?

```yaml
log_level: warn
no_color: true

projects:
  terraform:
    - name: AWS Development
      dir: aws/environments/development

    - name: AWS Stage
      dir: aws/environments/meta

    - name: AWS Production
      dir: aws/environments/prod

    - name: GCP Development
      dir: gcp/environments/development

    - name: GCP Stage
      dir: gcp/environments/meta

    - name: GCP Production
      dir: gcp/environments/prod

outputs:
  - format: table
    show_skipped: true
    group_by: project
```

**Comment by MrJoy** [comment]
That would be perfect, yes.

**Comment by alikhajeh1** [comment]
@MrJoy we shipped the config-file feature in the CLI, docs are [here](https://www.infracost.io/docs/config_file/). I've added support in this GH Action but haven't shipped the docs for it yet, can you possibly test it? We haven't added the "breakdown by project or module yet" feature yet, we're working on change to the underlying data structures to enable that...

In your github action yml, you can use the config like this to test it:
```
    - name: Run infracost diff
      uses: infracost/infracost-gh-action@master
      env:
        INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        config_file: infracost.yml # path to the config file in the repo, file needs to be in the master branch too
      with:
        entrypoint: /scripts/ci/diff.sh # Do not change
```
