### ISSUE TITLE
README.md example should use on: pull_request

### ISSUE THREAD

**Issue by mercuriete** [infracost/infracost-gh-action#18]
on https://github.com/infracost/infracost-gh-action/blame/master/README.md#L86

You have this example:

```
on:
  push:
    # This action runs on PRs, so no need to rerun it on master/main
    branches-ignore:
      - master
      - main
```

and it should be (one line and more clear):

```
on: pull_request
```

this was tested on my repository and it works perfectly.

thank you for this awesome tool.
