### ISSUE TITLE
[Feature Request] Allow to comment the commit even if the change is 0%

### ISSUE THREAD

**Issue by mercuriete** [infracost/infracost-gh-action#22]
Sometimes you add resources that don't change the infrastructure cost. But you want a feedback or reminder of the total cost with no diff.

Description:
I as a GitHub action I want to comment on a PR when the infrastructure cost has not changed.

example of yaml:
```
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@0.6.0
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: .
          entrypoint: /scripts/ci/diff.sh
          usage_file: infracost-usage.yml
          always_comment: true
```

Expected behavior:
* A comment is posted on a PR/commit even if the cost is 0% and diff is equal.

Actual behavior:
```
   Running infracost output using:
  $ infracost output --no-color --format diff --path infracost_breakdown.json
Comment not posted as diff (0%) is less than or equal to percentage threshold (0%).
```

Posible alternative implementation:
* Dont use <= is less than or equal to percentage threshold
* instead use < is less than to percentage threshold (strict <)

Thanks for your amazing work.

**Comment by alikhajeh1** [comment]
Good idea! I can see how some teams would want to be reminded of what the cost is, specially if it's a repo that is changed less often. Other teams we've spoken with prefer comments only on bigger thresholds to avoid too much noise.

Whilst I like the simplicity of [changing the logic](https://github.com/infracost/infracost/blob/master/scripts/ci/diff.sh#L233-L238) to use `<`, that would break the default behavior (only post comment if costs change).

Some other options:
1. introduce a new `always_post=true` param, which would mean percentage_threshold is ignored.

2. Change the semantics of `percentage_threshold` so that:
`0`: default, post comment when costs change.
`>0` values, e.g. 1: post when costs change by plus or minus 1%.
`-1`: a special constant to always post comments. Seems confusing. Also what if the user wants to set the threshold to -1% so only things that _reduce_ the cost by more than 1% trigger a comment?

3. Introduce a new `cost_threshold` param, e.g. post a comment when costs by more than $1K so someone can review. If we introduce this now, we could set it to `0` to always trigger comments. If `percentage_threshold` and `cost_threshold` are set, either triggers a comment.

I quite like option 3 as it's similar to 1 but more powerful. What do you think?

**Comment by mercuriete** [comment]
I tried yesterday with
percentage_threshold=-101

And It failed with no logs. (That is a perfect fine undefined behaviour).

This is why I opened this issue.

I like option 3.

I dont have any preference between your options.
I would say I will preffer the way is less expensive for your tema on terms of development.

Thanks for your work.

**Comment by jgrumboe** [comment]
I would vote for option 1 (always_post) and 3, but would not "abuse" option 3 (cost_treshold) to post always...although it's possible.
I like options that "explicitly" do what they are named for.

**Comment by alikhajeh1** [comment]
There's another use-case that I thought about for usage-based resources appearing in the diff. So I think a new `post_condition` variable that users can set to the following might work better:
- `always`: always post comments
- `has_diff`: only post comments whenever `infracost diff` has output (we can detect from the JSON output), this covers usage-based resources that have no costs but should appear in the PR comment.
- `percentage_threshold`: current functionality.
- in the future we can add `cost_threshold`.

`post_condition` can be a JSON string, e.g. `post_condition='{"always": "true"}'` or `post_condition='{"percentage_threshold": "2"}'` in bash (so `echo $post_condition | jq` should work). In future versions we can remove the old/top-level `percentage_threshold` variable.

**Comment by ekifel** [comment]
@alikhajeh1 Hey, I’d like to work on this!

**Comment by alikhajeh1** [comment]
@mercuriete and @jgrumboe see https://github.com/infracost/infracost-gh-action#post_condition in v0.7.0 of the GH Action for this, I marked the old percentage_threshold param as [deprecated](https://github.com/infracost/infracost-gh-action/blob/master/action.yml#L23-L24).

We'd appreciate feedback on the content of the PR comments themselves, e.g. if has_diff is used, the comment should probably be different if there are only usage-based resources?

**Comment by mercuriete** [comment]
I am pretty happy with the changes...

this is my configuration:

```
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@v0.7.0
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: .
          entrypoint: /scripts/ci/diff.sh
          usage_file: infracost-usage.yml
          post_condition: '{"always": true}'
```

this is the output:

moneybag Infracost estimate: monthly cost will increase by $0.00 (+0%) chart_with_upwards_trend

Previous monthly cost: $X
New monthly cost: $Y

Infracost output
```
Project: .

- aws_sns_topic.notifications-topic
  Cost depends on usage

    - Requests
      Cost depends on usage
        -$0.50 per 1M requests

Monthly cost change for .
Amount:  $0.00 ($X -> $Y)
Percent: 0%

----------------------------------
Key: ~ changed, + added, - removed

To estimate usage-based resources use --usage-file, see https://infracost.io/usage-file

2 resource types weren't estimated as they're not supported yet, rerun with --show-skipped to see.
Please watch/star https://github.com/infracost/infracost as new resources are added regularly.
```

I would prefer the entire report and not the diff but I am happy as is.
I think in this case it has diff because I deleted a sns_topic.

Thanks for your work.
