### ISSUE TITLE
Add Terraform init custom flags

### ISSUE THREAD

**Issue by garciasdos** [infracost/infracost-gh-action#24]
Hello, I'm trying to set up this awesome Action but I have a problem... My current tf configuration needs some custom flags to the `terraform init` path, and I'm seeing that the action only supports `terraform_plan_flags`. Would it be possible to add this configuration customizable too?

Thank you!!

**Comment by aliscott** [comment]
@garciasdos thanks 😄 ! What custom init flags do you use?

I think adding `terraform_init_flags` is a good idea. In the meantime you should be able to work around this by running terraform init before the Infracost action. Infracost only runs init if it hasn't already been run.

Something like this:

```yml
steps:
  - name: Check out repository
    uses: actions/checkout@v2
  
  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v1
  
  - name: Terraform Init
    run: terraform init <FLAGS>
    
  - name: Run infracost diff
    ...
```

**Comment by garciasdos** [comment]
@aliscott thank you for the fast answer! 

I've been trying to do what you've suggested but I'm into the same trouble. Here are my action steps:

```yaml
      - name: "Install terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
      - name: "Terraform init"
        run: terraform init -backend-config="credentials=`echo $SA_GCP`" -backend-config="prefix=`echo $APP_NAME`" -input=false
      - name: "Terraform plan"
        run: terraform plan -var="client_secret=`echo $SA_GCP`" -var="app_name=`echo $APP_NAME`"
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@master # Use a specific version instead of master if locking is preferred
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Do not change
          # See the cloud credentials section for the options
```

but it seems that the infracost action is still trying to `terraform plan`;
```
Running infracost breakdown using:
  $ infracost breakdown --no-color --format json --path ./
time="2021-04-28T13:04:30Z" level=info msg="Detected Terraform directory at ./"
time="2021-04-28T13:04:30Z" level=warning msg="Can't sync usage file as it's not specified"
time="2021-04-28T13:04:30Z" level=info msg="starting: Running terraform plan"
time="2021-04-28T13:04:30Z" level=info msg="Running command: /usr/bin/terraform plan -input=false -lock=false -no-color -out=/tmp/tfplan060661337"
time="2021-04-28T13:04:31Z" level=info msg="starting: Running terraform init"
time="2021-04-28T13:04:31Z" level=info msg="Running command: /usr/bin/terraform init -input=false -no-color"

  Terraform command failed with:
    Error: storage.NewClient() failed: dialing: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

Error: Error running terraform init: exit status 1
```

**Comment by aliscott** [comment]
Interesting, we have logic for only running init if it hasn't already run, so will look into why it is not detecting that.

One way to do this is just to generate and save the plan JSON file and then pass that in the `path` to Infracost.

```yml
      - name: "Install terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
      - name: "Terraform init"
        run: terraform init -backend-config="credentials=`echo $SA_GCP`" -backend-config="prefix=`echo $APP_NAME`" -input=false
      - name: "Terraform plan"
        run: terraform plan -var="client_secret=`echo $SA_GCP`" -var="app_name=`echo $APP_NAME`" -out plan.tfplan
      - name: "Terraform show"
        id: show
        run: terraform show -json plan.tfplan
      - name: "Save Plan JSON"
        run: echo '${{ steps.show.outputs.stdout }}' > plan.json
      - name: Run infracost diff
        uses: infracost/infracost-gh-action@master # Use a specific version instead of master if locking is preferred
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Do not change
          # See the cloud credentials section for the options
        with:
          entrypoint: /scripts/ci/diff.sh # Do not change
          path: plan.json
```

I've tested a full end-to-end example here: https://github.com/aliscott/gh-actions-demo/tree/pass-plan-json
