### ISSUE TITLE
How would one pass `--use-tfstate` option?

### ISSUE THREAD

**Issue by tovbinm** [infracost/infracost-gh-action#9]
In order to work with remote state one would need to [pass `--use-tfstate` option](https://github.com/infracost/infracost/pull/203) to `infracost` CLI. How can it be done with Github Actions?

**Comment by alikhajeh1** [comment]
@tovbinm thanks for creating this issue, I think #10 should work but I haven't had a chance to test it yet (was going to do tmrw). If you'd like to help test it, I think you can do the following in your GH Action to try the branch:
```
    - name: Run infracost diff
      uses: infracost/infracost-gh-action@add_tfstate
....
      with:
        use_tfstate: true
```

**Comment by tovbinm** [comment]
I haven't set `tfdir` since it's marked optional. I am not sure why the script complaints. 
```
Running infracost on master branch using:
  $ infracost --no-color --log-level warn --use-tfstate
Directory "/github/workspace" does not have any .tf files.
Set the Terraform directory path using the --tfdir option.
```

**Comment by tovbinm** [comment]
I tried passing `tfdir: .` and `tfdir: /` but I got the following error:
```
 Running infracost on master branch using:
  $ infracost --no-color --log-level warn --use-tfstate --tfdir /github/workspace/master//

  ⠋ Running terraform show time="2020-11-11T03:24:57Z" level=error
time="2020-11-11T03:24:57Z" level=error msg="Error: Initialization required. Please see the error message above."
time="2020-11-11T03:24:57Z" level=error
time="2020-11-11T03:24:57Z" level=error

  ✖ Running terraform show

  Terraform command failed with:
    Error: Initialization required. Please see the error message above.

Error running terraform show: exit status 1
```

**Comment by tovbinm** [comment]
Do I need to pass [Terraform Cloud credentials](https://www.terraform.io/docs/commands/cli-config.html#credentials)? How do I pass them into the Infracost container?

**Comment by alikhajeh1** [comment]
@tovbinm the `--use-tfstate` flag works by reading the statefile, and it looks like the above Terraform project is not init'd. Even if the creds are set, the project needs to be init'd, https://github.com/hashicorp/setup-terraform looks interesting, can you possibly try this:
1. in your GH repo, create a secret called `TF_API_TOKEN` and set it to your token.
2. add the following to your GH action yaml, before the infracost action runs:
```
steps:
- uses: hashicorp/setup-terraform@v1
  with:
    cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
- run: terraform init
uses: infracost/infracost-gh-action@add_tfstate
....
```

Also, can you possibly share a little about your overall use-case with us?

**Comment by tovbinm** [comment]
I will try that. I wonder why you did not have to run any of that in this project - https://github.com/infracost/ci-demo

**Comment by tovbinm** [comment]
I was able to initialize Terraformin in both folders, but it did not help:
```
- name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform init - master
        run: terraform init /home/runner/work/hephaestus/hephaestus/master

      - name: Terraform init - PR
        run: terraform init /home/runner/work/hephaestus/hephaestus/pull_request

      - name: Run Infracost diff
        uses: infracost/infracost-gh-action@add_tfstate
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          use_tfstate: true
          tfdir: /
```
I still got the same error - https://github.com/infracost/infracost-gh-action/issues/9#issuecomment-725116964

**Comment by alikhajeh1** [comment]
> I will try that. I wonder why you did not have to run any of that in this project - https://github.com/infracost/ci-demo

That repo uses plain `--tfdir` (which means infracost runs terraform init, plan then show), but passing `--use-tfstate` means that only show is needed as the state (.terraform/terraform.tfstate) can be used (that file is created when init runs).

Can you please try this, my previous suggestion was missing the working dir: 
```
      - name: Terraform init - master
        run: terraform init
        working-directory: /home/runner/work/my-tf/my-tf/master

      - name: Terraform init - PR
        run: terraform init
        working-directory: /home/runner/work/my-tf/my-tf/pull_request
```

**Comment by tovbinm** [comment]
I use `--use-tfstate` because I selected `Remote` as my `Execution Mode` on my Terraform Cloud workspace - https://www.terraform.io/docs/cloud/workspaces/settings.html#execution-mode

I.e. Terraform does not keep any state locally and runs all the commands in the cloud.

**Comment by alikhajeh1** [comment]
@tovbinm makes sense, plz lmk if setting `working-directory` helped

**Comment by tovbinm** [comment]
No, the same issue. Terraform init passed just fine for both branches, but not the Infracost step.

**Comment by alikhajeh1** [comment]
In this repo's README, for the two `actions/checkout@v2` steps, the `path` is set to `master` and `pull_request` and GH Actions default to cloning in `/github/workspace`, but I notice you're using `/home/runner/work/my-tf/my-tf/`, can those be changed to use the default github action workspace or does this GH Action need to be updated to make that a variable?

```
      - name: Terraform init - master
        run: terraform init
        working-directory: /github/workspace/master

      - name: Terraform init - PR
        run: terraform init
        working-directory: /github/workspace/pull_request
```

**Comment by tovbinm** [comment]
If I make this change, Terraform init fails with the following error: `Error: No such file or directory`.

**Comment by alikhajeh1** [comment]
can you possibly share the full yaml? I assume the init step is being run after the checkout?

**Comment by tovbinm** [comment]
```
on:
  pull_request:
    branches:
      - master
#     paths:
#       - '**.tf'
#       - '**.tfvars'
#       - '**.tfvars.json'
jobs:
  infracost:
    runs-on: ubuntu-latest
    name: Show infracost diff
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2.3.4
        with:
          ref: master
          path: master

      - name: Checkout pull request branch
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: pull_request

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      - name: Terraform init - master
        run: terraform init
        working-directory: /github/workspace/master
        env:
          TF_WORKSPACE: dev

      - name: Terraform init - PR
        run: terraform init
        working-directory: /github/workspace/pull_request
        env:
          TF_WORKSPACE: dev

      - name: Run Infracost diff
        uses: infracost/infracost-gh-action@add_tfstate
        env:
          INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          use_tfstate: true
          # tfdir: /
```
